@startuml

title API Calls
participant SDK as sdk
participant Webview as wv
participant "API\nServer" as api
participant "Authorization\nServer" as as

activate wv
    wv -> api: (access cookie)
    activate api 
        api -> api: get access token from cookie    
        api -> as: GET /api/auth/v1/jwks\n(cache for future)
            activate as
            as --> api: JWKs Data
        deactivate as
        api -> api: verify access token 
        api --> wv: API response
    deactivate api
deactivate wv   
break
activate sdk
    sdk -> api: Authorization: Bearer <access_token>
        api -> as: GET /api/auth/v1/jwks\n(cache for future)
        activate as
        as --> api: JWKs Data
    deactivate as
    api -> api: verify access token 
    api --> sdk: API response
deactivate 

@enduml