@startuml
title Hellō Login Flow (SDK)
actor User as user
participant SDK as sdk
participant Webview as wv
participant "Safe Browsing\nWindow" as sbw
participant "Hellō\nClient & AS" as hc
participant "Web\nServer" as ws
participant "User\nDB Service" as db
participant "Redis\nCache" as redis
participant "Hellō\nWallet" as hello

user -> sdk: Clicks Widget
activate sdk
  sdk -> wv: Open Webview
  activate wv
    wv -> ws: Fetch Homepage
    ws --> wv: Homepage
    wv -> hc: (A)\nPOST /token\ngrant_type=cookie_token&\nclient_id=webview_version
    activate hc
      hc -> hc: (1)\nno cookies
      hc -> redis: create new session, nonce
      redis --> hc:
      hc --> wv: loggedIn=false\nnonce
    deactivate hc
    wv --> user: Homepage, User Logged Out
    user -> wv: Clicks Login
    wv -> sdk: Start Login Flow\nnonce
  deactivate wv
    sdk -> sbw: (B)\nOpen Login Page\n\n/api/auth/v1?\nop=login&\nnonce=<nonce>&\nscope=<scopes>&\nprovider_hint=<provider_hints>&\ntarget_uri=<target_uri>
  deactivate sdk
  activate sbw
    sbw -> hc: open login page
    activate hc
      hc --> sbw: Hellō Login Redirect
      sbw -> hello: Fetch Login Page
      activate hello
        hello --> sbw: Hello Login Page
        sbw --> user: Hello Login Page
        user -> sbw: Authenticate
        sbw -> hello: Authenticate
        hello --> sbw: Authenticated\nRedirect to Hellō Client
        sbw -> hc: Auth Code from Hellō
        hc -> hello: Fetch ID Token with Auth Code
        hello --> hc: ID Token
      deactivate
        hc -> redis: (2)\nLookup nonce
        redis --> hc: nonce data
        hc -> db:  loginSync\n id_token, payload\n origin {client_id,target_uri}
        activate db
        db -> db: (C)\nCreate or\nupdate user\nprocess access
          db --> hc: target_uri, client_id, scope 
        deactivate db
        hc -> redis: Update nonce
        redis --> hc:
      hc --> sbw: Auth success
    sbw --> sdk: Auth success
  deactivate sbw
    activate sdk
    sdk -> hc: (D)\nPOST /api/auth/v1/token\ngrant_type=authorization_code&\ncode=nonce&\nclient_id=sdk_version
    hc -> redis: (3)\nLookup / upate nonce
    redis --> hc: nonce data
    hc -> hc: Future: check if\nuser logged out
    hc --> sdk: Access Token, Refresh Token
    sdk -> sdk: Store Tokens
    sdk --> wv: Open Webview
    activate wv
    wv -> ws: Fetch Homepage
    ws --> wv: Homepage
    wv -> hc: (E)\nPOST /api/auth/v1/token\ngrant_type=cookie_token&\nclient_id=webview_version
    hc --> redis: (4)\nLookup nonce
    redis --> hc: nonce data
    hc -> hc: Future: check if\nuser logged out
    hc --> wv: set access and refresh cookies\nloggedIn=true
    wv --> user: Home Page, User Logged In
    deactivate ws
  deactivate wv
  sdk -> hc: (F)\nPOST /api/auth/v1/token\ngrant_type=refresh_token&\nclient_id=sdk_version&\nrefresh_token=refresh_token
  hc -> hc: (5)\nFuture: check if\nuser logged out
  hc --> sdk: Access Token, Refresh Token
deactivate

@enduml